const material = [
  {
    id: '1',
    category: 'Pasir',
    shop: 'Hanil Jaya Stell',
    name: 'Pasir Pasang',
    ingredients: 'Pasir Pasang',
    image: require('../assets/Images/pasir.jpg'),
    price: '8.30',
    rating: '4.8',
    numReviews: '8',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '2',
    category: 'Batu',
    shop: 'Hanil Jaya Stell',
    name: 'Batu Coral',
    ingredients: 'Batu Coral',
    image: require('../assets/Images/batu.jpg'),
    price: '7.10',
    rating: '4.8',
    numReviews: '5',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '3',
    category: 'Genteng',
    shop: 'Hanil Jaya Stell',
    name: 'Genteng A Bagus',
    ingredients: 'Genteng A Bagus',
    image: require('../assets/Images/genteng.jpg'),
    price: '5.10',
    rating: '4.8',
    numReviews: '10',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '4',
    category: 'Besi',
    shop: 'Hanil Jaya Stell',
    name: 'Besi Beton',
    ingredients: 'Besi Beton',
    image: require('../assets/Images/besi.jpg'),
    price: '9.55',
    rating: '4.8',
    numReviews: '13',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },

  {
    id: '5',
    category: 'Semen',
    shop: 'Hanil Jaya Stell',
    name: 'Semen Tiga Roda',
    ingredients: 'Semen Tiga Roda',
    image: require('../assets/Images/semen.jpg'),
    price: '6.45',
    rating: '4.8',
    numReviews: '12',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '6',
    category: 'Keramik',
    name: 'Keramik Motif Marmer',
    ingredients: 'Keramik Motif Marmer',
    shop: 'Hanil Jaya Stell',
    image: require('../assets/Images/keramik.jpg'),
    price: '8.10',
    rating: '4.8',
    numReviews: '15',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '7',
    category: 'Pasir',
    shop: 'Hanil Jaya Stell',
    name: 'Pasir Pasang',
    ingredients: 'Pasir Pasang',
    image: require('../assets/Images/pasir.jpg'),
    price: '8.30',
    rating: '4.8',
    numReviews: '8',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '8',
    category: 'Batu',
    shop: 'Hanil Jaya Stell',
    name: 'Batu Coral',
    ingredients: 'Batu Coral',
    image: require('../assets/Images/batu.jpg'),
    price: '7.10',
    rating: '4.8',
    numReviews: '5',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '9',
    category: 'Genteng',
    shop: 'Hanil Jaya Stell',
    name: 'Genteng A Bagus',
    ingredients: 'Genteng A Bagus',
    image: require('../assets/Images/genteng.jpg'),
    price: '5.10',
    rating: '4.8',
    numReviews: '10',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '10',
    category: 'Besi',
    shop: 'Hanil Jaya Stell',
    name: 'Besi Beton',
    ingredients: 'Besi Beton',
    image: require('../assets/Images/besi.jpg'),
    price: '9.55',
    rating: '4.8',
    numReviews: '13',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },

  {
    id: '11',
    category: 'Semen',
    shop: 'Hanil Jaya Stell',
    name: 'Semen Tiga Roda',
    ingredients: 'Semen Tiga Roda',
    image: require('../assets/Images/semen.jpg'),
    price: '6.45',
    rating: '4.8',
    numReviews: '12',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
  {
    id: '12',
    category: 'Keramik',
    name: 'Keramik Motif Marmer',
    ingredients: 'Keramik Motif Marmer',
    shop: 'Hanil Jaya Stell',
    image: require('../assets/Images/keramik.jpg'),
    price: '8.10',
    rating: '4.8',
    numReviews: '15',
    address: 'Kota Surabaya',
    status: 'Barang sudah diterima customer',
    time: '30-03-2023 10.40',
  },
];

export default material;
